apiVersion: v1
kind: Pod
metadata:
  name: trimaran-test
spec:
  schedulerName: trimaran-scheduler
  containers:
  - name: test
    image: registry.access.redhat.com/ubi8/ubi
    command: ["echo", "UBI Started"]
  restartPolicy: Never
