- name: Configure user application monitoring
  command:
    oc apply -f {{ user_applications_monitor_config }}

- name: Ensure user monitoring enabled
  shell:
    set -o pipefail;

    oc -n openshift-user-workload-monitoring get pod
      | awk 'NR > 1 { print $3}'
  register: monitoring_enabled
  delay: 3
  retries: 20
  # until all of the pods are in the running state
  until: "'Completed' not in monitoring_enabled.stdout and 'Failed' not in monitoring_enabled.stdout and 'Pending' not in monitoring_enabled.stdout"

- name: Get Monitoring Secret
  shell:
    oc get secret -n openshift-user-workload-monitoring
      | grep  prometheus-user-workload-token
      | head -n 1
      | awk '{print $1 }'
  register: monitoring_secret
  delay: 3
  retries: 20
  until: "'prometheus-user-workload-token' in monitoring_secret.stdout"

- name: Get Thanos Endpoint
  shell:
    oc get route thanos-querier -n openshift-monitoring -o json
      | jq -r '.spec.host'
  register: thanos_endpoint
  delay: 3
  retries: 20
  until: "'thanos-querier' in thanos_endpoint.stdout"

- name: Deploy Trimaran scheduler
  shell: | 
    set -o errexit;
    set -o pipefail;
    set -o nounset;
    set -o errtrace;
   
    export THANOS_MONITORING_ENDPOINT={{ thanos_endpoint.stdout }}

    export MONITORING_SECRET={{ monitoring_secret.stdout }}

    export MONITORING_TOKEN=$(echo $(oc get secret $MONITORING_SECRET -n openshift-user-workload-monitoring -o json | jq -r '.data.token') | base64 -d)

    # Dumping stderr here can result in leaking the token 
    export TOKEN_SIZE=$(echo $MONITORING_TOKEN | wc -c 2> /dev/null)

    if [[ TOKEN_SIZE -ge 1000 ]]; then
      echo "DEPLOYING"  
      cat {{ trimaran_setup_config }} | envsubst | oc apply -f -
    else
      echo "SKIPPING: token looks malformed"
    fi

  register: deploy_trimaran
  delay: 5
  retries: 20
  until: "'DEPLOYING' in deploy_trimaran.stdout"

- name: Ensure Trimaran is Running
  shell:
    oc get pods -n trimaran | awk 'NR > 1 {print $3}'
  register: trimaran_running
  delay: 3
  retries: 20
  until: "trimaran_running.stdout == 'Running'"
