secrets:
  dir:
    name: null
    env_key: PSAP_ODS_SECRET_PATH
  s3_ldap_password_file: s3_ldap.passwords
tests:
  model_mesh:
    namespace: model-mesh-scale-test
    imagestream_name: scale-test
matbench:
  preset: null
  workload: rhods-notebooks
  config_file: notebook_scale_test_ods_ci.yaml # visualizations/rhods-notebooks/data
  download:
    mode: prefer_cache
    url:
    url_file:
    # if true, copy the results downloaded by `matbench download` into the artifacts directory
    save_to_artifacts: false
  ignore_exit_code: true
